resources:
  - name: repo_pipe
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: vijayreddy1991/utilityfunctiontests
      
  - name: repo_pipe1
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: vijayreddy1991/utilityfunctiontests      
      
pipelines:
  - name: utilityfuctiontest1
    steps:
      - name: step1
        type: Bash
        configuration:
          integrations:
            - name: s_gitHub
          inputResources:
            - name: repo_pipe
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute: 
            - printenv
            - bump_semver v3.0.0 major
            - bump_semver v3.0.0 minor
            - bump_semver v3.0.0 patch
            - bump_semver v3.0.0 beta
            - pushd $res_repo_pipe_resourcePath           
            - replace_envs $PWD/keys 
            - cat keys
            - echo "$scm"
            - cat terraform
            - compare_git --resource repo_pipe --commit-range HEAD~3..HEAD pipelines.yml
            - read_json package.json "DOCKER_USERNAME"
#             - write_output repo_pipe1 "imageTag=master" "sha=$commitSha" 
            - save_tests test.sh 
            - add_cache_files $PWD/terraform jfrog_pipe
            - restore_cache_files jfrog_pipe $PWD/terraform 
            - add_run_variables imageTag="master"
            - export_run_variables
            - export_pipeline_variables
            - add_run_files $PWD/terraform jfrog
            - add_pipeline_variables scm=$int_s_gitHub_masterName
            - add_pipeline_files $PWD/terraform jfrog_pipeline
            - find_resource_variable repo_pipe resourcePath
            - popd

      - name: step2
        type: Bash
        configuration:
          integrations:
            - name: s_gitHub
          inputSteps:
            - name: step1
          inputResources:
            - name: repo_pipe            
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute:
            - printenv
            - pushd $res_repo_pipe_resourcePath
            - restore_run_files jfrog $PWD/terraform
            - echo "$sha"

  - name: utilityfuctiontest2
    steps:
      - name: step3
        type: Bash
        configuration:
          integrations:
            - name: s_gitHub
          outputResources:
            - name: repo_pipe1
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute:
            - pushd $res_repo_pipe_resourcePath
            - replace_envs $PWD/keys
            - restore_pipeline_files jfrog_pipeline $PWD/terraform
            - execute_command [--retry] printen
            - retry_command printen
            - popd
